# Generated by Django 4.2.5 on 2023-10-14 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 14, 14, 39, 53, 250210, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
