# Generated by Django 4.2.5 on 2023-10-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemlist', '0002_alter_item_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Generator', 'Generator'), ('Panel', 'Panel'), ('ACs', 'ACs')], max_length=20),
        ),
    ]
