# Generated by Django 4.2.5 on 2023-10-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemlist', '0003_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Generator', 'Generator'), ('Panels', 'Panels'), ('ACs', 'ACs'), ('Inverters', 'Inverters'), ('Cables', 'Cables'), ('Lights', 'Lights'), ('Batteries', 'Batteries'), ('Others', 'Others')], max_length=20),
        ),
    ]
