# Generated by Django 4.2.5 on 2023-10-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemlist', '0004_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
